### PR TITLE
makes path to submodules relativly instead of absolute. Because of NPM 3

### PR DESCRIPTION
**Pull request by kwarkjes**
This PR should fix this issue:

``` bash
Running "iconfont:myTarget" (iconfont) task
Warning: Cannot find module '../node_modules/grunt-svgicons2svgfont/tasks/svgicons2svgfont.js' Use --force to continue.
```

### CODE REVIEW

**Comment by ninapavlich** [comment]
I am also experiencing the issue @kwarkjes observed, and using the code from the pull request worked successfully. Please merge this pull request when you can. Thanks @poppinlp!

**Comment by kwarkjes** [comment]
@poppinlp friendly reminder ;)

**Comment by poppinlp** [comment]
@kwarkjes 
Sry i forgot this.
I'm outside now and i'll publish tonight (GTM+8).

**Comment by poppinlp** [comment]
@kwarkjes 
Already published 0.2.2
THX.

**Pull request merged**
